name: Build slim packages

concurrency:
  group: slim-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - v*
      - e*
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        profile:
        - emqx-edge
        - emqx
        - emqx-enterprise
        otp:
        - 24.1.5-3
        os:
        - ubuntu20.04
        - centos7

    container: "ghcr.io/emqx/emqx-builder/5.0-3:${{ matrix.otp }}-${{ matrix.os }}"

    steps:
    - uses: actions/checkout@v1
    - name: rocksdb vsn
      run: |
        rebar3 get-deps
        RocksDBRef=$(erl -noshell -eval '{ok,Raw}=file:consult("rebar.lock"), {_Vsn, Deps}=hd(Raw), {_, {git, _Url, {ref, Ref}},_} = lists:keyfind(<<"rocksdb">>,1, Deps), io:format("~s",[Ref]), init:stop().')
        echo "::set-env name=DEP_ROCKSDB_REF::${RocksDBRef}"
        make clean-all
    - name: load rocksdb cache
      uses: actions/cache@v2
      with:
        path: _build/default/lib/rocksdb/
        key: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.otp }}-${DEP_ROCKSDB_REF}
    - name: build zip package
      run: make ${{ matrix.profile }}-zip
    - name: build deb/rpm packages
      run: make ${{ matrix.profile }}-pkg
    - name: packages test
      run: |
        export CODE_PATH=$GITHUB_WORKSPACE
        EMQX_NAME=${{ matrix.profile }} .ci/build_packages/tests.sh
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.profile}}-${{ matrix.otp }}-${{ matrix.os }}
        path: _packages/**/*.zip

  mac:

    strategy:
      fail-fast: false
      matrix:
        profile:
        - emqx
        - emqx-enterprise
        otp:
        - 24.1.5-3
        macos:
        - macos-11
        - macos-10.15

    runs-on: ${{  matrix.macos }}

    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: |
        brew update
        brew install curl zip unzip gnu-sed kerl unixodbc freetds
        echo "/usr/local/bin" >> $GITHUB_PATH
        echo "EMQX_NAME=${{ matrix.profile }}" >> $GITHUB_ENV
    - uses: actions/cache@v2
      id: cache
      with:
        path: ~/.kerl
        key: otp-${{ matrix.otp }}-${{ matrix.macos }}
    - name: build erlang
      if: steps.cache.outputs.cache-hit != 'true'
      timeout-minutes: 60
      env:
        KERL_BUILD_BACKEND: git
        OTP_GITHUB_URL: https://github.com/emqx/otp
      run: |
        kerl update releases
        kerl build ${{ matrix.otp }}
        kerl install ${{ matrix.otp }} $HOME/.kerl/${{ matrix.otp }}
    - name: build ${{ matrix.profile }}
      run: |
        . $HOME/.kerl/${{ matrix.otp }}/activate
        make ensure-rebar3
        sudo cp rebar3 /usr/local/bin/rebar3
        make ${{ matrix.profile }}-zip
    - name: test
      run: |
        pkg_name=$(find _packages/${{ matrix.profile }} -mindepth 1 -maxdepth 1 -iname \*.zip)
        unzip -q $pkg_name
        # gsed -i '/emqx_telemetry/d' ./emqx/data/loaded_plugins
        ./emqx/bin/emqx start || cat emqx/log/erlang.log.1
        ready='no'
        for i in {1..10}; do
          if curl -fs 127.0.0.1:18083/api/v5/status > /dev/null; then
            ready='yes'
            break
          fi
          sleep 1
        done
        if [ "$ready" != "yes" ]; then
          echo "Timed out waiting for emqx to be ready"
          cat emqx/log/erlang.log.1
          exit 1
        fi
        ./emqx/bin/emqx_ctl status
        ./emqx/bin/emqx stop
        rm -rf emqx
    - uses: actions/upload-artifact@v2
      with:
        name: macos
        path: _packages/**/*.zip
