name: Run test case

concurrency:
  group: test-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
    tags:
      - v*
      - e*
  pull_request:

jobs:
    run_proper_test:
        strategy:
          matrix:
            otp:
              - 24.1.5-4
            elixir:
              - 1.13.2
            os:
              - ubuntu20.04
            arch:
              - amd64

        runs-on: ubuntu-20.04
        container: "ghcr.io/emqx/emqx-builder/5.0-5:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}"

        steps:
        - uses: actions/checkout@v2

        - name: Get deps git refs for cache
          id: deps-refs
          run: |
            scripts/get-dep-refs.sh
            make clean-all
        - name: load rocksdb cache
          uses: actions/cache@v2
          with:
            path: source/_build/default/lib/rocksdb/
            key: ${{ matrix.os }}-${{ matrix.otp }}-${{ matrix.arch }}-${{ steps.deps-refs.outputs.DEP_ROCKSDB_REF }}
        - name: load quicer cache
          uses: actions/cache@v2
          with:
            path: source/_build/default/lib/quicer/
            key: ${{ matrix.os }}-${{ matrix.otp }}-${{ matrix.arch }}-${{ steps.deps-refs.outputs.DEP_QUICER_REF }}

        - name: proper
          run: make proper

    run_common_test:
        strategy:
          matrix:
            otp_release:
              - "erlang23"
              - "erlang24"

        runs-on: ubuntu-20.04

        steps:
        - uses: actions/checkout@v2
        - name: docker compose up
          env:
            MONGO_TAG: 5
            MYSQL_TAG: 8
            PGSQL_TAG: 13
            REDIS_TAG: 6
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            docker-compose \
                -f .ci/docker-compose-file/docker-compose-mongo-single-tcp.yaml \
                -f .ci/docker-compose-file/docker-compose-mongo-single-tls.yaml \
                -f .ci/docker-compose-file/docker-compose-mysql-tcp.yaml \
                -f .ci/docker-compose-file/docker-compose-mysql-tls.yaml \
                -f .ci/docker-compose-file/docker-compose-pgsql-tcp.yaml \
                -f .ci/docker-compose-file/docker-compose-pgsql-tls.yaml \
                -f .ci/docker-compose-file/docker-compose-redis-single-tcp.yaml \
                -f .ci/docker-compose-file/docker-compose-redis-single-tls.yaml \
                -f .ci/docker-compose-file/docker-compose.yaml \
                up -d --build
        - name: run eunit
          run: |
            docker exec -i ${{ matrix.otp_release }} bash -c "make eunit"
        - name: run common test
          run: |
            docker exec -i ${{ matrix.otp_release }} bash -c "make ct"
        - name: run cover
          run: |
            printenv > .env
            docker exec -i ${{ matrix.otp_release }} bash -c "DIAGNOSTIC=1 make cover"
            docker exec --env-file .env -i ${{ matrix.otp_release }} bash -c "DIAGNOSTIC=1 make coveralls"
        - name: cat rebar.crashdump
          if: failure()
          run: if [ -f 'rebar3.crashdump' ];then cat 'rebar3.crashdump'; fi
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs_${{ matrix.otp_release }}
            path: _build/test/logs
        - uses: actions/upload-artifact@v1
          with:
            name: cover_${{ matrix.otp_release }}
            path: _build/test/cover

    finish:
      needs: run_common_test
      runs-on: ubuntu-20.04
      steps:
        - name: Coveralls Finished
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            curl -v -k https://coveralls.io/webhook \
                 --header "Content-Type: application/json" \
                 --data "{\"repo_name\":\"$GITHUB_REPOSITORY\",\"repo_token\":\"$GITHUB_TOKEN\",\"payload\":{\"build_num\":$GITHUB_RUN_ID,\"status\":\"done\"}}" || true
